GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Harisenin",
    "email": "Harisenin@gmail.com",
    "gender": "Female"
}

###
PATCH http://localhost:5000/users/6
Content-Type: application/json

{
    "name": "Safitri",
    "email": "Safitri@gmail.com",
    "gender": "Female"
}

###
DELETE http://localhost:5000/users/11